// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetMind.API.Data;

#nullable disable

namespace PetMind.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108155045_AddRefreshTokenHash")]
    partial class AddRefreshTokenHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetMind.API.Models.Entities.Cachorro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContatoTutor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoCachorro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCachorro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTutor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetShopId")
                        .HasColumnType("int");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PetShopId");

                    b.ToTable("Cachorros");
                });

            modelBuilder.Entity("PetMind.API.Models.Entities.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Adicionais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CachorroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetShopId")
                        .HasColumnType("int");

                    b.Property<string>("ServicoBaseSelecionado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CachorroId");

                    b.HasIndex("PetShopId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("PetMind.API.Models.Entities.PetShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoPetShop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PetShops");
                });

            modelBuilder.Entity("PetMind.API.Models.Entities.Cachorro", b =>
                {
                    b.HasOne("PetMind.API.Models.Entities.PetShop", "PetShop")
                        .WithMany("Cachorros")
                        .HasForeignKey("PetShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PetShop");
                });

            modelBuilder.Entity("PetMind.API.Models.Entities.Horario", b =>
                {
                    b.HasOne("PetMind.API.Models.Entities.Cachorro", "Cachorro")
                        .WithMany()
                        .HasForeignKey("CachorroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetMind.API.Models.Entities.PetShop", "PetShop")
                        .WithMany("Horarios")
                        .HasForeignKey("PetShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cachorro");

                    b.Navigation("PetShop");
                });

            modelBuilder.Entity("PetMind.API.Models.Entities.PetShop", b =>
                {
                    b.Navigation("Cachorros");

                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
